/*
 *  Copyright 2007 Brian S O'Neill
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package dirmi.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * 
 *
 * @author Brian S O'Neill
 */
public class ClientStatement implements Statement {
    private final RemoteStatement mStatement;

    public ClientStatement(RemoteStatement st) {
        mStatement = st;
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        return new ClientResultSet(mStatement.executeQuery(sql));
    }

    public int executeUpdate(String sql) throws SQLException {
        return mStatement.executeUpdate(sql);
    }

    public void close() throws SQLException {
        mStatement.close();
    }

    public int getMaxFieldSize() throws SQLException {
        return mStatement.getMaxFieldSize();
    }

    public void setMaxFieldSize(int max) throws SQLException {
        mStatement.setMaxFieldSize(max);
    }

    public int getMaxRows() throws SQLException {
        return mStatement.getMaxRows();
    }

    public void setMaxRows(int max) throws SQLException {
        mStatement.setMaxRows(max);
    }

    public void setEscapeProcessing(boolean enable) throws SQLException {
        mStatement.setEscapeProcessing(enable);
    }

    public int getQueryTimeout() throws SQLException {
        return mStatement.getQueryTimeout();
    }

    public void setQueryTimeout(int seconds) throws SQLException {
        mStatement.setQueryTimeout(seconds);
    }

    public void cancel() throws SQLException {
        mStatement.cancel();
    }

    public SQLWarning getWarnings() throws SQLException {
        return mStatement.getWarnings();
    }

    public void clearWarnings() throws SQLException {
        mStatement.clearWarnings();
    }

    public void setCursorName(String name) throws SQLException {
        mStatement.setCursorName(name);
    }

    public boolean execute(String sql) throws SQLException {
        return mStatement.execute(sql);
    }

    public ResultSet getResultSet() throws SQLException {
        return new ClientResultSet(mStatement.getResultSet());
    } 

    public int getUpdateCount() throws SQLException {
        return mStatement.getUpdateCount();
    } 

    public boolean getMoreResults() throws SQLException {
        return mStatement.getMoreResults();
    } 

    public void setFetchDirection(int direction) throws SQLException {
        mStatement.setFetchDirection(direction);
    }

    public int getFetchDirection() throws SQLException {
        return mStatement.getFetchDirection();
    }

    public void setFetchSize(int rows) throws SQLException {
        mStatement.setFetchSize(rows);
    }
  
    public int getFetchSize() throws SQLException {
        return mStatement.getFetchSize();
    }

    public int getResultSetConcurrency() throws SQLException {
        return mStatement.getResultSetConcurrency();
    }

    public int getResultSetType()  throws SQLException {
        return mStatement.getResultSetType();
    }

    public void addBatch(String sql) throws SQLException {
        mStatement.addBatch(sql);
    }

    public void clearBatch() throws SQLException {
        mStatement.clearBatch();
    }

    public int[] executeBatch() throws SQLException {
        return mStatement.executeBatch();
    }

    public Connection getConnection() throws SQLException {
        throw unsupported();
    }

    public boolean getMoreResults(int current) throws SQLException {
        return mStatement.getMoreResults(current);
    }

    public ResultSet getGeneratedKeys() throws SQLException {
        return new ClientResultSet(mStatement.getGeneratedKeys());
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return mStatement.executeUpdate(sql, autoGeneratedKeys);
    }

    public int executeUpdate(String sql, int columnIndexes[]) throws SQLException {
        return mStatement.executeUpdate(sql, columnIndexes);
    }

    public int executeUpdate(String sql, String columnNames[]) throws SQLException {
        return mStatement.executeUpdate(sql, columnNames);
    }

    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return mStatement.execute(sql, autoGeneratedKeys);
    }

    public boolean execute(String sql, int columnIndexes[]) throws SQLException {
        return mStatement.execute(sql, columnIndexes);
    }

    public boolean execute(String sql, String columnNames[]) throws SQLException {
        return mStatement.execute(sql, columnNames);
    }

    public int getResultSetHoldability() throws SQLException {
        return mStatement.getResultSetHoldability();
    }

    public boolean isClosed() throws SQLException {
        return mStatement.isClosed();
    }

    public void setPoolable(boolean poolable) throws SQLException {
    }

    public boolean isPoolable() throws SQLException {
        return true;
    }

    public <T> T unwrap(Class<T> iface) throws SQLException {
        throw unsupported();
    }

    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return false;
    }

    private static SQLException unsupported() throws SQLException {
        return ClientDriver.unsupported();
    }
}
