/*
 *  Copyright 2007 Brian S O'Neill
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package dirmi.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;

import java.util.Properties;

/**
 * 
 *
 * @author Brian S O'Neill
 */
public class RemoteConnectionServer implements RemoteConnection {
    private final Connection mConnection;

    public RemoteConnectionServer(Connection con) {
        mConnection = con;
    }

    public RemoteStatement createStatement() throws SQLException {
        return new RemoteStatementServer(mConnection.createStatement());
    }

    public RemoteStatement createStatement(int resultSetType, int resultSetConcurrency) 
        throws SQLException
    {
        return new RemoteStatementServer
            (mConnection.createStatement(resultSetType,
                                         resultSetConcurrency));
    }

    public RemoteStatement createStatement(int resultSetType, int resultSetConcurrency, 
                                           int resultSetHoldability)
        throws SQLException
    {
        return new RemoteStatementServer
            (mConnection.createStatement(resultSetType,
                                         resultSetConcurrency,
                                         resultSetHoldability));
    }

    public RemotePreparedStatement prepareStatement(String sql)
        throws SQLException
    {
        return new RemotePreparedStatementServer(mConnection.prepareStatement(sql));
    }

    public RemotePreparedStatement prepareStatement(String sql, int resultSetType, 
                                                    int resultSetConcurrency)
        throws SQLException
    {
        return new RemotePreparedStatementServer
            (mConnection.prepareStatement(sql, resultSetType, resultSetConcurrency));
    }

    public RemotePreparedStatement prepareStatement(String sql, int resultSetType, 
                                                    int resultSetConcurrency,
                                                    int resultSetHoldability)
        throws SQLException
    {
        return new RemotePreparedStatementServer
            (mConnection.prepareStatement
             (sql, resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    public RemotePreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
        throws SQLException
    {
        return new RemotePreparedStatementServer
            (mConnection.prepareStatement(sql, autoGeneratedKeys));
    }

    public RemotePreparedStatement prepareStatement(String sql, int columnIndexes[])
        throws SQLException
    {
        return new RemotePreparedStatementServer(mConnection.prepareStatement(sql, columnIndexes));
    }

    public RemotePreparedStatement prepareStatement(String sql, String columnNames[])
        throws SQLException
    {
        return new RemotePreparedStatementServer(mConnection.prepareStatement(sql, columnNames));
    }

    public String nativeSQL(String sql) throws SQLException {
        return mConnection.nativeSQL(sql);
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        mConnection.setAutoCommit(autoCommit);
    }

    public boolean getAutoCommit() throws SQLException {
        return mConnection.getAutoCommit();
    }

    public void commit() throws SQLException {
        mConnection.commit();
    }

    public void rollback() throws SQLException {
        mConnection.rollback();
    }

    public void close() throws SQLException {
        mConnection.close();
    }

    public boolean isClosed() throws SQLException {
        return mConnection.isClosed();
    }

    public RemoteDatabaseMetaData getMetaData() throws SQLException {
        return new RemoteDatabaseMetaDataServer(mConnection.getMetaData());
    }

    public void setReadOnly(boolean readOnly) throws SQLException {
        mConnection.setReadOnly(readOnly);
    }

    public boolean isReadOnly() throws SQLException {
        return mConnection.isReadOnly();
    }

    public void setCatalog(String catalog) throws SQLException {
        mConnection.setCatalog(catalog);
    }

    public String getCatalog() throws SQLException {
        return mConnection.getCatalog();
    }

    public void setTransactionIsolation(int level) throws SQLException {
        mConnection.setTransactionIsolation(level);
    }

    public int getTransactionIsolation() throws SQLException {
        return mConnection.getTransactionIsolation();
    }

    public SQLWarning getWarnings() throws SQLException {
        return mConnection.getWarnings();
    }

    public void clearWarnings() throws SQLException {
        mConnection.clearWarnings();
    }

    public java.util.Map<String,Class<?>> getTypeMap() throws SQLException {
        return mConnection.getTypeMap();
    }

    public void setTypeMap(java.util.Map<String,Class<?>> map) throws SQLException {
        mConnection.setTypeMap(map);
    }

    public void setHoldability(int holdability) throws SQLException {
        mConnection.setHoldability(holdability);
    }

    public int getHoldability() throws SQLException {
        try {
            return mConnection.getHoldability();
        } catch (SQLException e) {
            // Driver workaround. Assume safe answer.
            return ResultSet.CLOSE_CURSORS_AT_COMMIT;
        }
    }

    public boolean isValid(int timeout) throws SQLException {
        return mConnection.isValid(timeout);
    }

    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        mConnection.setClientInfo(name, value);
    }
        
    public void setClientInfo(Properties properties)
        throws SQLClientInfoException
    {
        mConnection.setClientInfo(properties);
    }
        
    public String getClientInfo(String name) throws SQLException {
        return mConnection.getClientInfo(name);
    }
        
    public Properties getClientInfo() throws SQLException {
        return mConnection.getClientInfo();
    }      
}
